# Nginx ModSecurity entrypoint for your-domain.example
Include /etc/nginx/modsec/modsecurity.conf
Include /etc/modsecurity/crs/crs-setup.conf
Include /etc/nginx/modsec/crs-setup-panel.conf
Include /etc/nginx/modsec/panel-exclusions.conf
Include /etc/nginx/modsec/panel-clamav.conf
Include /usr/share/modsecurity-crs/rules/*.conf
Include /etc/nginx/modsec/panel-danger-log.conf
